---
addons:
  apt:
    packages:
      - libstdc++6
      - fonts-droid-fallback
    sources:
      - ubuntu-toolchain-r-test
after_success:
  - "coveralls-lcov coverage/lcov.info"
before_script:
  - "git clone https://github.com/flutter/flutter.git -b beta"
  - "./flutter/bin/flutter doctor"
  - "gem install coveralls-lcov"
cache:
  directories:
    - $HOME/.pub-cache
os:
  - linux
script:
  - ./flutter/bin/flutter test --coverage test/unit_tests/* test/widget_tests/*
sudo: false
